<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Basic blocks for building algorithms and data structures.
Commonly used types:
- Color
- Endpoints&lt;TVertex&gt;
- EqualityComparerEquatable&lt;T, TComparer&gt;</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>graph;primitive</PackageTags>
    <Title>Stable primitive types</Title>
    <VersionSuffix>preview</VersionSuffix>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyVersion>0.17</AssemblyVersion>
    <FileVersion>$(VersionPrefix)</FileVersion>
    <TargetFrameworks>net462;netstandard2.0;netstandard2.1</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(DebugType)' == 'portable'">
    <EmbedAllSources>true</EmbedAllSources>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <Import Condition="'$(TargetFramework)' == 'net462' OR '$(TargetFramework)' == 'netstandard2.0'" Project="..\Shared\NullableAttributes\NullableAttributes.projitems" Label="Shared" />

</Project>
